<?php

namespace GS\ProyectosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BibliografiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibliografiaRepository extends EntityRepository
{
     public function buscarUltimoBibliografia() {//Traer el ultimo registro hecho en la base de datos
        return $this->getEntityManager()
                        ->createQuery('SELECT b.idbibliografia FROM GSProyectosBundle:Bibliografia b ORDER BY b.idbibliografia DESC')
                        ->setMaxResults(1)
                        ->getResult();
    }
}
