<?php

namespace GS\ProyectosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LecturaconpropositoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LecturaconpropositoRepository extends EntityRepository
{
    public function buscarUltimaLectura() {//Traer el ultimo registro hecho en la base de datos
        return $this->getEntityManager()
                        ->createQuery('SELECT p.idlecturaconproposito FROM GSProyectosBundle:Lecturaconproposito p ORDER BY p.idlecturaconproposito DESC')
                        ->setMaxResults(1)
                        ->getResult();
    }
}
