<?php

namespace GS\ProyectosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MensajerecibidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajerecibidoRepository extends EntityRepository {

    public function buscarUltimoMensajeRecibido() {//Traer el ultimo registro hecho en la base de datos
        return $this->getEntityManager()
                        ->createQuery('SELECT c.idmensajerecibido FROM GSProyectosBundle:Mensajerecibido c ORDER BY c.idmensajerecibido DESC')
                        ->setMaxResults(1)
                        ->getResult();
    }

    public function contarMensajesNoLeidos($usuario) {
        return $this->getEntityManager()
                        ->createQuery('SELECT COUNT(mr.idmensajerecibido) FROM GSProyectosBundle:Mensajerecibido mr WHERE mr.para = :usuario AND mr.revisado = false')
                        ->setParameter('usuario', $usuario)
                        ->getSingleScalarResult();
    }

}
