<?php

namespace GS\ProyectosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduccionintelectualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionintelectualRepository extends EntityRepository {

    public function buscarUltimoProduccionIntelectual() {//Traer el ultimo registro hecho en la base de datos
        return $this->getEntityManager()
                        ->createQuery('SELECT p.idproduccionintelectual FROM GSProyectosBundle:ProduccionIntelectual p ORDER BY p.idproduccionintelectual DESC')
                        ->setMaxResults(1)
                        ->getResult();
    }

    /*
     * Buscar la produccion intelectual del usuario a nivel del grupo.
     * Se recibe el numeroDocumentoIdentidad correspondiente al modelo Usuario
     * y el limite o tamaño del numero de resultados que devolvera la consulta.
     */

    public function buscarProduccionUsuario($usuario, $limite) {
        return $this->getEntityManager()
                        ->createQuery('SELECT p FROM GSProyectosBundle:Produccionintelectual p JOIN GSProyectosBundle:TemaUsuario tu WITH tu.usuario = :numeroDocumentoIdentidad AND tu.tema = p.tema ORDER BY p.fecharegistro DESC')
                        ->setParameter('numeroDocumentoIdentidad', $usuario)
                        ->setMaxResults($limite)
                        ->getResult();
    }

    /*
     * Buscar producción por parametro de busqueda. 
     */

    public function buscarProduccionParametro($tamano, $parametro) {
        return $this->getEntityManager()
                        ->createQuery('SELECT u FROM GSProyectosBundle:Produccionintelectual u WHERE  (u.titulo LIKE :titulo  OR u.palabrasclave LIKE :palabraclave)')
                        ->setParameter('titulo', '%' . $parametro . '%')
                        ->setParameter('palabraclave', '%' . $parametro . '%')
                        ->setMaxResults($tamano)
                        ->getResult();
    }

    /*
     * Buscar producción intelectual realizada en el año en curso
     */

    public function buscarProduccionAnoCurso() {
        $ano = \date('Y');

        return $this->getEntityManager()
                        ->createQuery('SELECT u FROM GSProyectosBundle:Produccionintelectual u WHERE  u.fecharegistro LIKE :ano ORDER BY u.fecharegistro DESC')
                        ->setParameter('ano', '%' . $ano . '%')
                        ->getResult();
    }

}
