<?php

namespace GS\ProyectosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduccionintelectualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionintelectualRepository extends EntityRepository {

    public function buscarUltimoProduccionIntelectual() {//Traer el ultimo registro hecho en la base de datos
        return $this->getEntityManager()
                        ->createQuery('SELECT p.idproduccionintelectual FROM GSProyectosBundle:ProduccionIntelectual p ORDER BY p.idproduccionintelectual DESC')
                        ->setMaxResults(1)
                        ->getResult();
    }

    /*
     * Buscar la produccion intelectual del usuario a nivel del grupo.
     * Se recibe el numeroDocumentoIdentidad correspondiente al modelo Usuario
     * y el limite o tamaño del numero de resultados que devolvera la consulta.
     */

    public function buscarProduccionUsuario($usuario, $limite) {
        return $this->getEntityManager()
                        ->createQuery('SELECT p FROM GSProyectosBundle:Produccionintelectual p JOIN GSProyectosBundle:TemaUsuario tu WITH tu.usuario = :numeroDocumentoIdentidad AND tu.tema = p.tema ORDER BY p.fecharegistro DESC')
                        ->setParameter('numeroDocumentoIdentidad', $usuario )                
                        ->setMaxResults($limite)
                        ->getResult();
    }

}
