<?php

namespace GS\ProyectosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemaUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaUsuarioRepository extends EntityRepository
{
    public function buscarUltimoTemaUsuario() {//Traer el ultimo registro hecho en la base de datos
        return $this->getEntityManager()
                        ->createQuery('SELECT u.idtemaUsuario FROM GSProyectosBundle:TemaUsuario u ORDER BY u.idtemaUsuario DESC')
                        ->setMaxResults(1)
                        ->getResult();
    }
}
