<?php

namespace GS\ProyectosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemaBibliografiaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaBibliografiaRepository extends EntityRepository
{
     public function buscarUltimoTemaBibliografia() {//Traer el ultimo registro hecho en la base de datos
        return $this->getEntityManager()
                        ->createQuery('SELECT c.idtemaBibliografia FROM GSProyectosBundle:TemaBibliografia c ORDER BY c.idtemaBibliografia DESC')
                        ->setMaxResults(1)
                        ->getResult();
    }
}
