<?php

namespace GS\ProyectosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaRepository extends EntityRepository {
    /*
     * Buscar usuario desde el panel de aministración de usuarios. 
     */

    public function buscarTema($parametro, $limite) {
        return $this->getEntityManager()
                        ->createQuery('SELECT t FROM GSProyectosBundle:Tema t WHERE t.titulo LIKE :parametro ORDER BY t.idtema DESC')
                        ->setParameter('parametro', '%' . $parametro . '%')                
                        ->setMaxResults($limite)
                        ->getResult();
    }

}
