<?php

namespace GS\ConsultasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduccionintelectualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionintelectualRepository extends EntityRepository
{
     /*
     * Consulta para la busqueda avanzada de la produccion intelectual 
     
     */
    public function busquedaAvanzada($estado,$titulo,$tipoproduccion,$numeroresultados,$primernombre,$primerapellido) {
        $dql = "SELECT p FROM GSConsultasBundle:Usuario u JOIN GSConsultasBundle:TemaUsuario e WITH e.usuario = u.numerodocumentoidentidad JOIN GSConsultasBundle:Produccionintelectual p WITH p.tema = e.tema JOIN GSConsultasBundle:Tema ti WITH p.tema = ti.idtema AND "
                . "((u.primernombre LIKE :primernombre AND u.primerapellido LIKE :primerapellido)OR "
                . "(u.primernombre LIKE :primernombre AND p.titulo LIKE :titulo)OR "
                . "(u.primernombre LIKE :primernombre AND p.tipoproduccion = :tipoproduccion)OR "
                . "(u.primerapellido LIKE :primerapellido AND p.titulo LIKE :titulo)OR "
                . "(u.primerapellido LIKE :primerapellido AND p.tipoproduccion = :tipoproduccion)OR "
                . "(p.titulo LIKE :titulo AND p.tipoproduccion = :tipoproduccion)OR "
                . "(u.primernombre LIKE :primernombre AND u.primerapellido LIKE :primerapellido AND p.titulo LIKE :titulo)OR "
                . "(u.primernombre LIKE :primernombre AND u.primerapellido LIKE :primerapellido AND p.tipoproduccion = :tipoproduccion)OR "
                . "(u.primerapellido LIKE :primerapellido AND p.titulo LIKE :titulo AND p.tipoproduccion = :tipoproduccion)OR "
                . "(u.primernombre LIKE :primernombre AND p.titulo LIKE :titulo AND p.tipoproduccion = :tipoproduccion)OR "
                . "(u.primernombre LIKE :primernombre AND u.primerapellido LIKE :primerapellido AND p.titulo LIKE :titulo AND p.tipoproduccion = :tipoproduccion))OR p.estado=:estado"; 
                

        return $this->getEntityManager()
                        ->createQuery($dql)//toma los valores para la consulta de la url
                        ->setParameter('estado', $estado)
                        ->setParameter('titulo', '%' . $titulo . '%')
                        ->setParameter('tipoproduccion',$tipoproduccion )
                        ->setParameter('primernombre',$primernombre )
                        ->setParameter('primerapellido',$primerapellido )
                        ->setMaxResults($numeroresultados*4)//maneja el numero de resultados que se visualizaran 
                        ->getResult();
    }
}
