<?php

namespace GS\ConsultasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecursosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecursosRepository extends EntityRepository
{
 
    /*
     * Consulta para la busqueda avanzada de los recursos
     
     */
    public function busquedaAvanzada($nombre,$tiporecurso,$numeroresultados)
    {
        $em = $this->getEntityManager();
        $dql = "select r
            from GSConsultasBundle:Recursos r
            where(r.tiporecurso=:tiporecurso AND r.nombre LIKE :nombre)";
        
        $query = $em->createQuery($dql);
        $query->setParameter('nombre', '%' . $nombre . '%');
        $query->setParameter('tiporecurso', $tiporecurso);
        $query->setMaxResults($numeroresultados);
        $recursos = $query->getResult();
        return $recursos;
    }
}
