<?php

namespace GS\ConsultasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository {

    public function busquedaAvanzada($numerodocumentoidentidad, $primernombre, $segundonombre, $primerapellido, $segundoapellido,$numeroresultados) {

    /*
     * Consulta para la busqueda avanzada de los usuarios
     
     */
        $dql = "SELECT u FROM GSConsultasBundle:Usuario u "
                . "WHERE u.numerodocumentoidentidad = :numerodocumentoidentidad OR((u.primernombre LIKE :primernombre AND u.segundonombre LIKE :segundonombre)OR "
                . "(u.primernombre LIKE :primernombre AND u.primerapellido LIKE :primerapellido) OR "
                . "(u.primerapellido LIKE :primerapellido AND u.segundoapellido LIKE :segundoapellido) OR "
                . "(u.segundonombre LIKE :segundonombre AND u.primerapellido LIKE :primerapellido) OR " 
                . "(u.primernombre LIKE :primernombre AND u.segundonombre LIKE :segundonombre AND u.primerapellido LIKE :primerapellido) OR "
                . "(u.primernombre LIKE :primernombre AND u.primerapellido LIKE :primerapellido AND u.segundoapellido LIKE :segundoapellido) OR "
                . "(u.segundonombre LIKE :segundonombre AND u.primerapellido LIKE :primerapellido AND u.segundoapellido LIKE :segundoapellido) OR "
                . "(u.primernombre LIKE :primernombre AND u.segundonombre LIKE :segundonombre AND u.primerapellido LIKE :primerapellido AND u.segundoapellido LIKE :segundoapellido))";
                 

        return $this->getEntityManager()
                        ->createQuery($dql)
                        ->setParameter('numerodocumentoidentidad', $numerodocumentoidentidad)
                        ->setParameter('primernombre', '%' . $primernombre . '%')
                        ->setParameter('segundonombre', '%' . $segundonombre . '%')
                        ->setParameter('primerapellido', '%' . $primerapellido . '%')
                        ->setParameter('segundoapellido', '%' . $segundoapellido . '%')
                       // ->setParameter('email', '%' . $email . '%')
                        ->setMaxResults($numeroresultados)
                        ->getResult();
    }
    
    /*
     * Consulta para la busqueda avanzada de los usuarios, con mas opciones por medio de la funcion ver mas 
     
     */
    
        public function verMas($numerodocumentoidentidad, $primernombre, $segundonombre, $primerapellido, $segundoapellido) {
            
        $dql = "SELECT u FROM GSConsultasBundle:Usuario u "
                . "WHERE u.numerodocumentoidentidad = :numerodocumentoidentidad AND((u.primernombre LIKE :primernombre AND u.segundonombre LIKE :segundonombre)OR "
                . "(u.primernombre LIKE :primernombre AND u.primerapellido LIKE :primerapellido) OR "
                . "(u.primerapellido LIKE :primerapellido AND u.segundoapellido LIKE :segundoapellido) OR "
                . "(u.segundonombre LIKE :segundonombre AND u.primerapellido LIKE :primerapellido) OR " 
                . "(u.primernombre LIKE :primernombre AND u.segundonombre LIKE :segundonombre AND u.primerapellido LIKE :primerapellido) OR "
                . "(u.primernombre LIKE :primernombre AND u.primerapellido LIKE :primerapellido AND u.segundoapellido LIKE :segundoapellido) OR "
                . "(u.segundonombre LIKE :segundonombre AND u.primerapellido LIKE :primerapellido AND u.segundoapellido LIKE :segundoapellido) OR "
                . "(u.primernombre LIKE :primernombre AND u.segundonombre LIKE :segundonombre AND u.primerapellido LIKE :primerapellido AND u.segundoapellido LIKE :segundoapellido))";
                
        return $this->getEntityManager()
                        ->createQuery($dql)
                        ->setParameter('numerodocumentoidentidad', $numerodocumentoidentidad)
                        ->setParameter('primernombre', '%' . $primernombre . '%')
                        ->setParameter('segundonombre', '%' . $segundonombre . '%')
                        ->setParameter('primerapellido', '%' . $primerapellido . '%')
                        ->setParameter('segundoapellido', '%' . $segundoapellido . '%')
                        ->getResult();
    }

}
