<?php

namespace GS\ContenidosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduccionintelectualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionintelectualRepository extends EntityRepository {

    public function buscarProduccion($tamano, $parametro) {
        return $this->getEntityManager()
                        ->createQuery('SELECT u FROM GSContenidosBundle:Produccionintelectual u WHERE u.titulo LIKE :titulo  OR u.palabrasclave LIKE :palabraclave')
                        ->setParameter('titulo', '%' . $parametro . '%')
                        ->setParameter('palabraclave', '%' . $parametro . '%')
                        ->setMaxResults($tamano)
                        ->getResult();
    }

}
