<?php

namespace GS\ContenidosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduccionintelectualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionintelectualRepository extends EntityRepository {

    public function buscarProduccion($tamano, $parametro) {
        return $this->getEntityManager()
                        ->createQuery('SELECT u FROM GSContenidosBundle:Produccionintelectual u WHERE u.estado = true AND (u.titulo LIKE :titulo  OR u.palabrasclave LIKE :palabraclave)')
                        ->setParameter('titulo', '%' . $parametro . '%')
                        ->setParameter('palabraclave', '%' . $parametro . '%')
                        ->setMaxResults($tamano)
                        ->getResult();
    }
    
     /*
     * Buscar la produccion intelectual del usuario a nivel del grupo.
     * Se recibe el numeroDocumentoIdentidad correspondiente al modelo Usuario
     * y el limite o tamaño del numero de resultados que devolvera la consulta.
     */

    public function buscarProduccionUsuario($usuario, $limite) {
        return $this->getEntityManager()
                        ->createQuery('SELECT p FROM GSContenidosBundle:Produccionintelectual p JOIN GSContenidosBundle:TemaUsuario tu WITH p.estado = true tu.usuario = :numeroDocumentoIdentidad AND tu.tema = p.tema ORDER BY p.fecharegistro DESC')
                        ->setParameter('numeroDocumentoIdentidad', $usuario )                
                        ->setMaxResults($limite)
                        ->getResult();
    }

}
