<?php

namespace GS\ContenidosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaRepository extends EntityRepository {
    /*
     * Buscar los temas ofertados por el grupo. 
     * Estos temas son los que no tiene un usuario asignado.
     */

    public function buscarTemaOfertado() {
        return $this->getEntityManager()
                        ->createQuery('SELECT t FROM GSContenidosBundle:Tema t WHERE NOT EXISTS(SELECT tu FROM GSContenidosBundle:TemaUsuario tu WHERE t.idtema = tu.tema ORDER BY t.fecharegistro DESC)')
                        ->getResult();
    }

    /*
     * Buscar la produccion intelectual del usuario a nivel del grupo.
     * Se recibe el numeroDocumentoIdentidad correspondiente al modelo Usuario
     * y el limite o tamaño del numero de resultados que devolvera la consulta.
     */

    public function buscarUltimosTemasOfertados() {
        return $this->getEntityManager()
                        ->createQuery('SELECT t FROM GSContenidosBundle:Tema t WHERE NOT EXISTS(SELECT tu FROM GSContenidosBundle:TemaUsuario tu WHERE t.idtema = tu.tema ORDER BY t.fecharegistro DESC)')
                        ->setMaxResults(3)
                        ->getResult();
    }

}
